// <auto-generated />
using System;
using Backk;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backk.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009202051_migration001")]
    partial class migration001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backk.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salario")
                        .HasColumnType("float");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backk.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Backk.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantidad_productos")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_pedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_cliente_pedidoid")
                        .HasColumnType("int");

                    b.Property<int?>("id_producto_pedido_2id")
                        .HasColumnType("int");

                    b.Property<int?>("id_producto_pedido_3id")
                        .HasColumnType("int");

                    b.Property<int?>("id_producto_pedido_4id")
                        .HasColumnType("int");

                    b.Property<int?>("id_producto_pedido_5id")
                        .HasColumnType("int");

                    b.Property<int>("id_producto_pedidoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("id_cliente_pedidoid");

                    b.HasIndex("id_producto_pedido_2id");

                    b.HasIndex("id_producto_pedido_3id");

                    b.HasIndex("id_producto_pedido_4id");

                    b.HasIndex("id_producto_pedido_5id");

                    b.HasIndex("id_producto_pedidoid");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Backk.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("almacenamiento")
                        .HasColumnType("float");

                    b.Property<int>("disponibilidad")
                        .HasColumnType("int");

                    b.Property<string>("marca_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Producto");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backk.CelularNuevo", b =>
                {
                    b.HasBaseType("Backk.Producto");

                    b.Property<string>("garantia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CelularNuevo");
                });

            modelBuilder.Entity("Backk.CelularUsado", b =>
                {
                    b.HasBaseType("Backk.Producto");

                    b.Property<string>("condicion_bat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CelularUsado");
                });

            modelBuilder.Entity("Backk.Notebook", b =>
                {
                    b.HasBaseType("Backk.Producto");

                    b.Property<double>("cm_alto")
                        .HasColumnType("float");

                    b.Property<double>("cm_ancho")
                        .HasColumnType("float");

                    b.Property<string>("idioma_teclado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Notebook");
                });

            modelBuilder.Entity("Backk.Pedido", b =>
                {
                    b.HasOne("Backk.Cliente", "id_cliente_pedido")
                        .WithMany()
                        .HasForeignKey("id_cliente_pedidoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backk.Producto", "id_producto_pedido_2")
                        .WithMany()
                        .HasForeignKey("id_producto_pedido_2id");

                    b.HasOne("Backk.Producto", "id_producto_pedido_3")
                        .WithMany()
                        .HasForeignKey("id_producto_pedido_3id");

                    b.HasOne("Backk.Producto", "id_producto_pedido_4")
                        .WithMany()
                        .HasForeignKey("id_producto_pedido_4id");

                    b.HasOne("Backk.Producto", "id_producto_pedido_5")
                        .WithMany()
                        .HasForeignKey("id_producto_pedido_5id");

                    b.HasOne("Backk.Producto", "id_producto_pedido")
                        .WithMany()
                        .HasForeignKey("id_producto_pedidoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id_cliente_pedido");

                    b.Navigation("id_producto_pedido");

                    b.Navigation("id_producto_pedido_2");

                    b.Navigation("id_producto_pedido_3");

                    b.Navigation("id_producto_pedido_4");

                    b.Navigation("id_producto_pedido_5");
                });
#pragma warning restore 612, 618
        }
    }
}
